export const ADD_DECK = 'ADD_DECK'
export const ADD_DECK_TO_STORAGE = 'ADD_DECK_TO_STORAGE'
export const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK'
export const GET_DECKS = 'GET_DECKS'
export const SEND_CARD = 'SEND_CARD'